# 应用服务 WEB 访问端口
server.port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 600000
      connection-test-query: SELECT 1
      auto-commit: true